skip_commits:
  message: /\[circleci\]/

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"
    PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"
      ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda update conda -y
  - conda install conda-build -y
  - conda config --add channels conda-forge
  - conda config --add channels menpo
  - python --version

build_script:
  - "%CMD_IN_ENV% conda build libnetcdf-feedstock/recipe --py 3.4"
  # - "%CMD_IN_ENV% conda build openblas"
  - "%CMD_IN_ENV% conda build recipe --py 3.4"
  # - "%CMD_IN_ENV% C:/msys64/usr/bin/make libcpptraj"
  # - "%CMD_IN_ENV% C:/msys64/usr/bin/make"

test_script:
  - echo "nothing to test"
  - echo "hello"

after_build:
  - 7z a cpptraj-%APPVEYOR_BUILD_ID%.zip bin/* src/*.h lib/*

artifacts:
  - path: cpptraj-$(APPVEYOR_BUILD_ID).zip
