skip_commits:
  message: /\[circleci\]/

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"
    PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"
      ARCH: "64"

install:
  - set HOME=.
  - set MSYSTEM=MINGW64
  - set PATH=C:/msys64/usr/bin;C:/msys64/mingw64/bin;%PATH%
  - "sh -lc \"pacman -S --noconfirm --needed
      mingw-w64-x86_64-openblas
      mingw-w64-x86_64-arpack
      mingw-w64-x86_64-gcc
      mingw-w64-x86_64-gcc-fortran
      mingw-w64-x86_64-ncurses
      mingw-w64-x86_64-readline
      diffutils
    \""
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda update conda -y
  - conda install conda-build -y
  - conda create -n py34 python=3.4 -y
  - activate py34
  - conda config --add channels conda-forge
  - conda install mingwpy -y
  - python -c "import sys; print(sys.prefix)"
  - python --version
  - conda install bzip2 -y
  - where g++
  - g++ -v

build_script:
  - "%CMD_IN_ENV% bash configure -noreadline -nonetcdf -nobzlib -nomathlib -shared gnu"
  - "%CMD_IN_ENV% make libcpptraj"
  - "%CMD_IN_ENV% make"

test_script:
  - echo "nothing to test"

after_build:
  - 7z a cpptraj-%APPVEYOR_BUILD_ID%.zip bin/* src/*.h lib/*
  - find C:/msys64/usr/local

artifacts:
  - path: cpptraj-$(APPVEYOR_BUILD_ID).zip
